stages:
- build
- test

cc7:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - yum install -y gcc-c++ cmake3 make rpm-build which git yum-plugin-priorities yum-utils
    - packaging/gitlab-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

fedora24:
  stage: build
  image: fedora:24
  script:
    - dnf install -y gcc-c++ cmake3 make rpm-build which git yum-plugin-priorities yum-utils
    - packaging/gitlab-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

ubuntu-asan:
  stage: build
  image: ubuntu:16.10
  script:
    - ./utils/ubuntu-asan.sh
  artifacts:
    paths:
    - build/coverage-report

cc7-test:
  stage: test
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  dependencies:
  - cc7
  script:
    - yum -y localinstall cc7/RPMS/*
    - quarkdb-tests
    - quarkdb-stress-tests

fedora24-test:
  stage: test
  image: fedora:24
  dependencies:
  - fedora24
  script:
    - dnf -y install fedora24/RPMS/*
    - quarkdb-tests
    - quarkdb-stress-tests
