stages:
- build

cc7-enhanced:
  stage: build
  image: gitlab-registry.cern.ch/vcs/gitlabci-docker-builder
  variables:
    TO: gitlab-registry.cern.ch/eos/quarkdb/cc7-enhanced
    DOCKER_FILE: cc7-enhanced/Dockerfile
  script:
  - ""
  tags:
  - docker-image-build

