stages:
- build

cc7-enhanced:
  stage: build
  variables:
    TO: gitlab-registry.cern.ch/eos/quarkdb/cc7-enhanced
    DOCKER_FILE: cc7-enhanced/Dockerfile
    NO_CACHE: "1"
  script:
  - ""
  tags:
  - docker-image-build

ubuntu-enhanced:
  stage: build
  variables:
    TO: gitlab-registry.cern.ch/eos/quarkdb/ubuntu-enhanced
    DOCKER_FILE: ubuntu-enhanced/Dockerfile
    NO_CACHE: "1"
  script:
  - ""
  tags:
  - docker-image-build


