site_name: QuarkDB Documentation
theme:
  name: null
  custom_dir: '../deps/mkdocs-material/material'
  language: en

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

  palette:
  font:
    text: Roboto
    code: Roboto Mono
  logo:
    icon: "\uE80C"
  feature:
    tabs: true

nav:
  - Home: index.md
  - Getting started:
    - Installation: installation.md
    - Configuration: configuration.md
    - Troubleshooting: troubleshooting.md
  - Operator's manual:
    - Version upgrades: upgrading.md
    - Backup & restore: backup.md
  - Configuration:
    - Password authentication: authentication.md
    - Journal trimming: journal-trimming.md
    - Resilvering: resilvering.md
    - Fsync policy: fsync.md
    - Bulkload mode: bulkload.md
    - Membership updates: membership.md
  - Advanced topics:
    - Raft basics: raft.md
    - Write path: write-path.md
    - Raft extensions: raft-extensions.md
  - Release notes: release-notes.md
